name: nde-pymeasure
channels:
  - defaults
dependencies:
  - python=3.7.16
  - pip
  - pip:
    - pymeasure
    - pyserial # added new libraries below
    - pandas
    - numpy
    - scipy
    - matplotlib